'use server'

import { revalidatePath } from 'next/cache'
import { auditLog } from '@/lib/audit'
import { priceCheckout } from '@/lib/checkoutPricing'
import { createServerSupabaseClient, createAdminSupabaseClient } from '@/lib/supabase'
import { requireAdmin } from './auth'
import { checkoutSchema } from '@/lib/validations'
import { getCart } from './cart'
import { getStoreSettings } from './settings'
import { sendOrderCancellationEmail, sendRefundEmail } from '@/lib/email'
import { sendSlackAlert } from '@/lib/slack'
import { setPaymentStatusInternal, restoreOrderStock, cancelOrderInternal, issueGatewayRefund, releaseCouponUsage, recordRefund } from '@/lib/orders-internal'
import { notifyUser } from '@/lib/notifications'
import { enqueue } from '@/lib/jobs'
import type { OrderWithItems, Order, OrderItem } from '@/types/database'
import type { SupabaseClient } from '@supabase/supabase-js'

// Not exported — a 'use server' file exposes every exported async function as
// a client-callable RPC, and this is only ever meant to run right after
// cancelOrderInternal succeeds, never invoked directly by a client.
async function notifyCancellation(orderId: string, refundIssued: boolean) {
  const admin = createAdminSupabaseClient()
  const { data: order } = await admin.from('orders').select('email, order_number, refunded_amount').eq('id', orderId).single()
  if (!order) return
  await sendOrderCancellationEmail({
    email: order.email,
    orderNumber: order.order_number,
    refunded: refundIssued,
    refundAmount: refundIssued ? order.refunded_amount : undefined,
  }).catch(() => {})
}

// Fires the order-confirmation email once a payment actually clears. Called from
// each payment-success path (Stripe webhook, Razorpay webhook, Razorpay's client
// callback) — those three can race for the same order, so callers are responsible
// for only invoking this the first time payment_status transitions to 'paid' (see
// the `alreadyPaid` checks at each call site). Best-effort: a failed email should
// never fail the payment confirmation itself, so callers should swallow errors.

// Best-effort — checked right after checkout decrements stock via the DB
// trigger, since that's the one moment stock is known to have just moved.
// A failure here should never affect an order that already succeeded.
async function checkLowStockAndAlert(items: { product_id: string; variant_id: string | null }[]) {
  const admin = createAdminSupabaseClient()
  const productIds = [...new Set(items.map((i) => i.product_id))]
  const variantIds = [...new Set(items.map((i) => i.variant_id).filter((v): v is string => Boolean(v)))]

  const { data: products } = await admin
    .from('products')
    .select('name, inventory_quantity, low_stock_threshold')
    .in('id', productIds)

  const { data: variants } = variantIds.length
    ? await admin.from('product_variants').select('name, inventory_quantity, low_stock_threshold, product:products!inner(name)').in('id', variantIds)
    : { data: [] as Record<string, unknown>[] }

  const lowItems = [
    ...(products ?? [])
      .filter((p) => p.inventory_quantity != null && p.inventory_quantity <= (p.low_stock_threshold ?? 5))
      .map((p) => `${p.name} (${p.inventory_quantity} left)`),
    ...(variants ?? []).flatMap((raw) => {
      const v = raw as { name: string; inventory_quantity: number | null; low_stock_threshold: number | null; product: { name: string } | null }
      if (v.inventory_quantity == null || v.inventory_quantity > (v.low_stock_threshold ?? 5)) return []
      return [`${v.product?.name ?? 'Unknown product'} — ${v.name} (${v.inventory_quantity} left)`]
    }),
  ]

  if (lowItems.length > 0) {
    await sendSlackAlert(`:warning: Low stock after checkout: ${lowItems.join(', ')}`)
  }
}

export async function createOrder(input: {
  userId?: string | null
  sessionId?: string | null
  email: string
  phone?: string
  shipping_address_id: string
  billing_address_id?: string
  coupon_code?: string
  notes?: string
  payment_method: 'stripe' | 'razorpay' | 'cod'
  /** One per checkout ATTEMPT, generated by the caller. A retry of the same
   *  attempt carries the same key and returns the original order instead of
   *  placing a second one; a genuine second order gets a new key. */
  idempotencyKey?: string
  // Only set by the mobile checkout route, which has no cookie session for
  // RLS to key off (auth.uid() would be null). It passes the admin client
  // here instead — safe because the address it references was just inserted
  // by that same route for this exact token-verified user, not supplied
  // by the caller as an arbitrary id.
  client?: SupabaseClient
}) {
  const parsed = checkoutSchema.safeParse(input)
  if (!parsed.success) return { error: parsed.error.flatten().fieldErrors }

  // Two clients, deliberately: `supabase` stays session-scoped so the address
  // lookups below stay RLS-restricted to addresses the caller actually owns
  // (auth.uid() = user_id) — using the admin client there would let anyone pass
  // someone else's address id. `admin` is used only for the writes that place
  // the order itself (orders/order_items/coupon_usages), since those tables'
  // INSERT policies are scoped to service_role — see migration 012.
  const supabase = input.client ?? await createServerSupabaseClient()
  const admin = createAdminSupabaseClient()

  // A double-clicked pay button, a retried mobile request, or a network retry
  // after the write landed but the response was lost all arrive here again. Any
  // of them would otherwise place a second order and decrement stock twice.
  if (input.idempotencyKey) {
    const { data: existing } = await admin
      .from('orders')
      .select('id, order_number')
      .eq('idempotency_key', input.idempotencyKey)
      .maybeSingle()
    if (existing) return { orderId: existing.id, orderNumber: existing.order_number, replayed: true as const }
  }

  const cart = await getCart(input.userId, input.sessionId, input.client)
  if (!cart?.items?.length) return { error: 'Cart is empty' }

  const { data: shippingAddress } = await supabase
    .from('addresses').select('*').eq('id', parsed.data.shipping_address_id).single()
  if (!shippingAddress) return { error: 'Shipping address not found' }

  // Priced by the same function the checkout screen quotes from, so the number
  // the customer approved and the number they are billed cannot drift apart.
  // See lib/checkoutPricing.ts for why that is one function and not two.
  const priced = await priceCheckout({
    items: cart.items,
    destination: { state: shippingAddress.state, country: shippingAddress.country },
    couponCode: parsed.data.coupon_code,
    userId: input.userId ?? undefined,
    client: input.client,
  })
  if ('error' in priced) return { error: priced.error }

  const {
    subtotal, effectiveShipping: effective_shipping, discountAmount: discount_amount,
    taxAmount: tax_amount, totalAmount: total_amount, taxByLine,
  } = priced
  const taxResult = { breakdown: priced.taxBreakdown }
  const interState = priced.taxIsIgst

  let billingAddress = shippingAddress
  if (parsed.data.billing_address_id) {
    const { data: ba } = await supabase.from('addresses').select('*').eq('id', parsed.data.billing_address_id).single()
    if (ba) billingAddress = ba
  }

  const { data: order, error: orderError } = await admin.from('orders').insert({
    user_id: input.userId, email: parsed.data.email, phone: parsed.data.phone,
    subtotal, shipping_cost: effective_shipping, tax_amount, discount_amount, total_amount,
    tax_breakdown: taxResult.breakdown, tax_is_igst: interState,
    shipping_address: shippingAddress, billing_address: billingAddress,
    notes: parsed.data.notes, payment_method: parsed.data.payment_method,
    idempotency_key: input.idempotencyKey ?? null,
  }).select().single()

  // The pre-check above closes the common case; this closes the race where two
  // requests with the same key arrive close enough together that both read
  // "no existing order" before either wrote. The unique index is the real
  // guarantee — 23505 here means the other request won, so return its order
  // rather than surfacing a database error to someone who just paid.
  if (orderError) {
    if (orderError.code === '23505' && input.idempotencyKey) {
      const { data: winner } = await admin
        .from('orders')
        .select('id, order_number')
        .eq('idempotency_key', input.idempotencyKey)
        .maybeSingle()
      if (winner) return { orderId: winner.id, orderNumber: winner.order_number, replayed: true as const }
    }
    return { error: orderError.message }
  }

  const orderItems = cart.items.map((item) => ({
    order_id: order.id, product_id: item.product_id, variant_id: item.variant_id,
    custom_design_id: item.custom_design_id,
    product_name: item.product.name, variant_name: item.variant?.name ?? null,
    sku: item.variant?.sku ?? item.product.sku,
    unit_price: item.product.price + (item.variant?.price_adjustment ?? 0),
    quantity: item.quantity,
    total_price: (item.product.price + (item.variant?.price_adjustment ?? 0)) * item.quantity,
    // Snapshotted with the line, like product_name and unit_price already are:
    // an invoice must keep saying what was charged even after the rate table
    // or the product's classification changes.
    hsn_code: item.product.hsn_code ?? null,
    tax_rate: taxByLine.get(item.id)?.rate ?? 0,
    taxable_value: taxByLine.get(item.id)?.taxableValue ?? 0,
    tax_amount: taxByLine.get(item.id)?.taxAmount ?? 0,
  }))

  // What each campaign actually cost, per order.
  if (priced.promotions.length) {
    await admin.from('order_promotions').insert(
      priced.promotions.map((a) => ({
        order_id: order.id, promotion_id: a.promotionId, label: a.label, amount: a.amount,
      }))
    )
  }

  const { error: itemsError } = await admin.from('order_items').insert(orderItems)
  if (itemsError) {
    await admin.from('orders').delete().eq('id', order.id)
    // 23514 = check_violation — the products/product_variants inventory floor
    // constraint (021_stock_integrity.sql) rejected the order_items insert
    // trigger's decrement because an item sold out between add-to-cart and
    // checkout. The raw Postgres message ("violates check constraint...") is
    // not something to show a customer; this is the real out-of-stock path.
    if (itemsError.code === '23514') {
      return { error: 'One or more items in your cart just sold out — please update your cart and try again.' }
    }
    return { error: itemsError.message }
  }

  await checkLowStockAndAlert(orderItems.map((i) => ({ product_id: i.product_id, variant_id: i.variant_id }))).catch(() => {})

  if (parsed.data.coupon_code && discount_amount > 0) {
    const { data: coupon } = await supabase.from('coupons').select('id').eq('code', parsed.data.coupon_code.toUpperCase()).single()
    if (coupon) {
      await admin.from('coupon_usages').insert({ coupon_id: coupon.id, user_id: input.userId, order_id: order.id, discount_amount })
      await admin.rpc('increment_coupon_usage', { coupon_id: coupon.id })
    }
  }

  if (input.userId) {
    await supabase.from('cart_items').delete().eq('cart_id', cart.id)
    // The cart row survives the order, so its recovery flags have to be cleared
    // here or this customer could never be chased again — one abandonment in
    // March would have silenced the reminder for every cart after it.
    await admin
      .from('carts')
      .update({ recovery_token: null, recovery_sent_at: null, recovered_at: null })
      .eq('id', cart.id)
  }

  // COD is confirmed the moment it is placed — there is no gateway callback
  // coming to do it later. The three existing `order.confirmation` enqueues all
  // live in gateway success handlers, so a COD customer placed an order and
  // heard nothing at all: no confirmation, no order number, no record they
  // could point at. On the payment method this shop advertises most.
  if (parsed.data.payment_method === 'cod') {
    await admin
      .from('orders')
      .update({ status: 'confirmed', confirmed_at: new Date().toISOString() })
      .eq('id', order.id)
    await enqueue('order.confirmation', { orderId: order.id })
  }

  revalidatePath('/orders')
  return { success: true, orderId: order.id }
}

// userId is required here — this is the customer-facing lookup (only caller
// is the /account/orders/[id] page), and without an ownership check any
// signed-in user who knows or guesses another order's UUID could read its
// shipping address and tracking info. Admin order lookups go through
// getAllOrders/the admin client instead, which don't need this.
export async function getOrder(orderId: string, userId: string) {
  const supabase = await createServerSupabaseClient()
  const { data, error } = await supabase
    .from('orders')
    .select('*, items:order_items(*, design:custom_designs(*), product:products(images))')
    .eq('id', orderId)
    .eq('user_id', userId)
    .single()
  if (error) return null
  return data as unknown as OrderWithItems
}

/** One row per order, for the spreadsheet every ops team lives in.
 *
 *  Returns a string rather than writing a file: the caller turns it into a
 *  download, and nothing touches disk on a serverless box. Respects the active
 *  view so "export what I am looking at" is the default behaviour.
 *
 *  Money is divided to rupees here on purpose — this is the one place a human
 *  reads the number directly, and paise in a spreadsheet get misread as rupees. */
export async function exportOrdersCsv(options?: { view?: OrderView; search?: string }) {
  await requireAdmin()
  const { orders } = await getAllOrders({ ...options, limit: 5000, offset: 0 })

  const header = [
    'Order', 'Date', 'Customer', 'Phone', 'Status', 'Payment', 'Method',
    'Items', 'Subtotal', 'Shipping', 'Tax', 'Discount', 'Total', 'City', 'State', 'Pincode',
  ]

  // Quote everything and double internal quotes: an address with a comma in it
  // would otherwise silently shift every later column by one.
  const cell = (v: unknown) => `"${String(v ?? '').replace(/"/g, '""')}"`
  const rupees = (paise: number | null | undefined) => ((paise ?? 0) / 100).toFixed(2)

  const rows = orders.map((o) => {
    const a = (o.shipping_address ?? {}) as Record<string, string>
    return [
      o.order_number,
      new Date(o.created_at).toISOString().slice(0, 10),
      a.full_name ?? o.email,
      a.phone ?? o.phone ?? '',
      o.status,
      o.payment_status,
      o.payment_method ?? '',
      (o.items ?? []).reduce((n, i) => n + i.quantity, 0),
      rupees(o.subtotal), rupees(o.shipping_cost), rupees(o.tax_amount),
      rupees(o.discount_amount), rupees(o.total_amount),
      a.city ?? '', a.state ?? '', a.postal_code ?? '',
    ].map(cell).join(',')
  })

  return [header.map(cell).join(','), ...rows].join('\n')
}

/** Admin single-order fetch. Deliberately separate from getOrder(), which is
 *  scoped to the caller's own user_id — an admin looking at a customer's order
 *  is not that customer, so reusing it would silently return nothing. */
export async function getOrderForAdmin(orderId: string) {
  await requireAdmin()
  const { data } = await createAdminSupabaseClient()
    .from('orders')
    .select('*, items:order_items(*, design:custom_designs(*), product:products(images))')
    .eq('id', orderId)
    .single()
  return (data as unknown as OrderWithItems) ?? null
}

export async function getOrderByNumber(orderNumber: string) {
  const supabase = await createServerSupabaseClient()
  const { data, error } = await supabase.from('orders').select('*, items:order_items(*)').eq('order_number', orderNumber).single()
  if (error) return null
  return data as unknown as OrderWithItems
}

export async function getUserOrders(userId: string, limit = 10, offset = 0) {
  const supabase = await createServerSupabaseClient()
  const { data, error, count } = await supabase
    .from('orders')
    .select('*, items:order_items(*)', { count: 'exact' })
    .eq('user_id', userId)
    .order('created_at', { ascending: false })
    .range(offset, offset + limit - 1)
  if (error) throw new Error(error.message)
  return { orders: (data ?? []) as unknown as OrderListRow[], total: count ?? 0 }
}

export async function updateOrderStatus(orderId: string, status: Order['status']) {
  const actor = await requireAdmin()

  // Cancelling is never a bare status flip — it has to restore stock, release
  // any coupon usage, and refund the gateway charge if one was captured, so it
  // always routes through the same shared path bulk cancel and the customer's
  // own cancelOrder() use, rather than just writing `status` here and leaving
  // all of that undone (which is what this function used to do).
  if (status === 'cancelled') {
    const result = await cancelOrderInternal(orderId, { cancelledBy: 'admin' })
    if ('error' in result) throw new Error(result.error)
    await notifyCancellation(orderId, result.refundIssued)
    revalidatePath(`/admin/orders/${orderId}`)
    revalidatePath(`/orders/${orderId}`)
    return
  }

  const supabase = createAdminSupabaseClient()
  const { data: prior } = await supabase.from('orders').select('status').eq('id', orderId).single()
  const previousStatus = prior?.status ?? null
  const updates: Partial<Order> = { status }
  if (status === 'confirmed') updates.confirmed_at = new Date().toISOString()
  if (status === 'shipped') updates.shipped_at = new Date().toISOString()
  if (status === 'delivered') updates.delivered_at = new Date().toISOString()
  const { data: order, error } = await supabase
    .from('orders')
    .update(updates)
    .eq('id', orderId)
    .select('user_id, order_number')
    .single()
  if (error) throw new Error(error.message)
  revalidatePath(`/admin/orders/${orderId}`)
  revalidatePath(`/orders/${orderId}`)
  // Who moved this order, and from what. Previously unanswerable.
  await auditLog({
    actorId: actor.id, actorEmail: actor.email, action: 'order.status_changed',
    entityType: 'order', entityId: orderId,
    before: { status: previousStatus }, after: { status },
  })
  await notifyOrderStatus(orderId, order?.user_id, order?.order_number, status)
}

const ORDER_STATUS_NOTIFICATION: Partial<Record<Order['status'], string>> = {
  confirmed: 'has been confirmed',
  processing: 'is being processed',
  shipped: 'is on its way',
  delivered: 'has been delivered',
}

// Shared by updateOrderStatus and addTrackingInfo — both can independently
// transition an order to 'shipped', so the notification copy lives in one
// place rather than being duplicated (and drifting) at each call site.
async function notifyOrderStatus(orderId: string, userId: string | null | undefined, orderNumber: string | undefined, status: Order['status']) {
  const phrase = ORDER_STATUS_NOTIFICATION[status]
  if (!userId || !orderNumber || !phrase) return
  await notifyUser({
    userId,
    type: 'order_update',
    title: `Order ${orderNumber} ${phrase}`,
    orderId,
    data: { orderNumber },
  }).catch(() => {})
}

// Dedicated admin-facing cancel action (distinct from the generic
// updateOrderStatus) so a future per-order "Cancel" button in the admin UI
// can surface the gateway-refund result directly instead of just a toast.
export async function cancelOrderAsAdmin(orderId: string, reason?: string) {
  const actor = await requireAdmin()
  const result = await cancelOrderInternal(orderId, { reason, cancelledBy: 'admin' })
  if ('error' in result) return result
  // Cancellation restores stock, releases the coupon and may refund — a
  // compound reversal that is worth being able to attribute to a person.
  await auditLog({
    actorId: actor.id, actorEmail: actor.email, action: 'order.cancelled',
    entityType: 'order', entityId: orderId,
    after: { refundIssued: result.refundIssued }, note: reason,
  })
  await notifyCancellation(orderId, result.refundIssued)
  revalidatePath('/admin/orders')
  revalidatePath(`/orders/${orderId}`)
  return { success: true, refundIssued: result.refundIssued }
}

// Admin-facing manual override only (e.g. a future "mark as paid" button in
// the admin order view) — requires a real admin session. Webhooks and
// customer-side payment verification use setPaymentStatusInternal directly;
// they're trusted by gateway signature verification, not a user session, so
// gating them behind requireAdmin() here made every payment confirmation
// throw and silently leave every order stuck 'pending' forever.
export async function updatePaymentStatus(orderId: string, paymentStatus: Order['payment_status'], paymentIntentId?: string) {
  await requireAdmin()
  await setPaymentStatusInternal(orderId, paymentStatus, { gatewayOrderId: paymentIntentId })
}

// The queues an ops team actually works from, rather than raw status values.
// "Unfulfilled" is the daily worklist; "COD pending" is money not yet collected;
// "RTO" is stock coming back that someone has to receive. Each is a question
// with a real answer, which is what separates a saved view from a filter.
export type OrderView = 'all' | 'unfulfilled' | 'cod_pending' | 'rto' | 'needs_attention'

const UNFULFILLED: string[] = ['pending', 'confirmed', 'processing']

// What the list and the CSV export between them actually read.
//
// The old select was `*` plus every order_item column plus each item's four
// custom-design URLs — the print files. None of that is on screen: a row shows
// "Custom Hoodie +2 more" and a unit count, and the artwork lives on the detail
// page. Measured at 5.1KB for two orders against 1.3KB for the columns in use,
// and it scales with items per order, so a busy day made the list heavier.
const ORDER_LIST_COLUMNS =
  'id, order_number, email, phone, status, payment_status, payment_method, ' +
  'subtotal, shipping_cost, tax_amount, discount_amount, total_amount, ' +
  'created_at, refund_needs_attention, shipping_address, phone_digits, ' +
  'items:order_items(quantity, product_name, custom_design_id)'

/** Exactly what ORDER_LIST_COLUMNS returns, so the table cannot start reading a
 *  field the query stopped fetching. */
export type OrderListRow = Pick<
  Order,
  | 'id' | 'order_number' | 'email' | 'phone' | 'status' | 'payment_status'
  | 'payment_method' | 'subtotal' | 'shipping_cost' | 'tax_amount'
  | 'discount_amount' | 'total_amount' | 'created_at'
  | 'refund_needs_attention' | 'shipping_address'
> & {
  items: Pick<OrderItem, 'quantity' | 'product_name' | 'custom_design_id'>[]
}

export async function getAllOrders(options?: { status?: string; needsAttention?: boolean; view?: OrderView; search?: string; limit?: number; offset?: number }) {
  await requireAdmin()
  const supabase = createAdminSupabaseClient()
  let query = supabase
    .from('orders')
    .select(ORDER_LIST_COLUMNS, { count: 'exact' })
    .order('created_at', { ascending: false })
  const view = options?.view ?? (options?.needsAttention ? 'needs_attention' : 'all')
  if (view === 'needs_attention') query = query.eq('refund_needs_attention', true)
  else if (view === 'unfulfilled') query = query.in('status', UNFULFILLED)
  else if (view === 'cod_pending') query = query.eq('payment_method', 'cod').eq('payment_status', 'pending')
  else if (view === 'rto') {
    // RTO lives on the parcel, not the order, so this resolves the order ids
    // first rather than trying to express it as a join filter.
    const { data: rto } = await supabase.from('shipments').select('order_id').eq('status', 'rto')
    const ids = [...new Set((rto ?? []).map((r) => r.order_id))]
    if (ids.length === 0) return { orders: [], total: 0 }
    query = query.in('id', ids)
  } else if (options?.status) query = query.eq('status', options.status)
  if (options?.search) {
    // Strip the LIKE wildcards so a stray % cannot turn a search into a table
    // scan, and the comma too — PostgREST's `.or()` is comma-delimited, so an
    // unescaped one would be read as another filter.
    const term = options.search.replace(/[%_,]/g, '').trim()
    const filters = [
      `order_number.ilike.%${term}%`,
      `email.ilike.%${term}%`,
      `shipping_address->>full_name.ilike.%${term}%`,
    ]
    // A phone is matched on its last ten digits — the national number, however
    // the customer wrote it. See migration 046: the stored value has a leading
    // zero and the column `phone` is usually null, the number living in the
    // address JSON. Six digits is enough to be a deliberate phone fragment
    // rather than an order-number stub.
    const digits = term.replace(/\D/g, '')
    if (digits.length >= 6) filters.push(`phone_digits.like.%${digits.slice(-10)}%`)

    query = query.or(filters.join(','))
  }
  if (options?.limit != null && options?.offset != null) {
    query = query.range(options.offset, options.offset + options.limit - 1)
  } else if (options?.limit) {
    query = query.limit(options.limit)
  }
  const { data, error, count } = await query
  if (error) throw new Error(error.message)
  return { orders: (data ?? []) as unknown as OrderListRow[], total: count ?? 0 }
}

// Powers the "Needs Attention" banner in /admin/orders — a lightweight count
// so the page doesn't have to load a full order page just to know whether to
// show it.
export async function getRefundAttentionCount() {
  await requireAdmin()
  const supabase = createAdminSupabaseClient()
  const { count } = await supabase
    .from('orders')
    .select('*', { count: 'exact', head: true })
    .eq('refund_needs_attention', true)
  return count ?? 0
}

export async function bulkUpdateOrderStatus(orderIds: string[], status: Order['status']) {
  await requireAdmin()

  // Same reasoning as updateOrderStatus: a bulk "mark cancelled" used to be a
  // single raw UPDATE that never restored stock, never released coupon usage,
  // and never refunded a captured charge — for a whole batch of orders at
  // once. Each one needs its own gateway refund call, so this can't stay a
  // single bulk UPDATE; run them individually and report how many failed
  // rather than letting one bad order silently swallow the rest.
  if (status === 'cancelled') {
    const outcomes = await Promise.all(
      orderIds.map(async (id) => {
        const result = await cancelOrderInternal(id, { cancelledBy: 'admin' })
        if ('success' in result) await notifyCancellation(id, result.refundIssued)
        return result
      })
    )
    revalidatePath('/admin/orders')
    const failedCount = outcomes.filter((r) => 'error' in r).length
    if (failedCount > 0) {
      throw new Error(`${failedCount} of ${orderIds.length} order${orderIds.length === 1 ? '' : 's'} could not be cancelled`)
    }
    return
  }

  const supabase = createAdminSupabaseClient()
  const updates: Partial<Order> = { status }
  if (status === 'confirmed') updates.confirmed_at = new Date().toISOString()
  if (status === 'delivered') updates.delivered_at = new Date().toISOString()
  const { error } = await supabase.from('orders').update(updates).in('id', orderIds)
  if (error) throw new Error(error.message)
  revalidatePath('/admin/orders')
}



// addTrackingInfo lived here. It wrote carrier/tracking_number/tracking_url
// straight onto the order, which became a SECOND source of truth once shipments
// existed — the customer page had to guess which to believe, and an order could
// disagree with its own parcel. Shipping now goes through actions/shipments.ts;
// the legacy columns are read-only fallbacks for pre-shipments orders, and
// migration 032 backfilled those into real shipments.

export async function cancelOrder(orderId: string, userId: string, reason?: string) {
  const supabase = await createServerSupabaseClient()
  const { data: owned } = await supabase.from('orders').select('id').eq('id', orderId).eq('user_id', userId).single()
  if (!owned) return { error: 'Order not found' }

  const result = await cancelOrderInternal(orderId, { reason, cancelledBy: 'customer' })
  if ('error' in result) return result

  await notifyCancellation(orderId, result.refundIssued)
  revalidatePath(`/account/orders/${orderId}`)
  revalidatePath('/admin/orders')
  return { success: true }
}

// Issues a real refund at the payment gateway (Stripe/Razorpay — COD orders skip
// straight to bookkeeping since there's no charge to reverse), then restores stock.
// Amount defaults to the full order total; a smaller amount marks the order
// partially_refunded instead of refunded.
export async function refundOrder(orderId: string, options?: { amount?: number; restock?: boolean; reason?: string }) {
  const actor = await requireAdmin()
  const admin = createAdminSupabaseClient()

  const { data: order } = await admin.from('orders').select('*').eq('id', orderId).single()
  if (!order) return { error: 'Order not found' }
  if (order.payment_status === 'refunded') return { error: 'Order is already fully refunded' }
  if (order.payment_status !== 'paid' && order.payment_status !== 'partially_refunded') {
    return { error: 'Only paid orders can be refunded' }
  }

  // Bounded by what's actually left to refund, not the order total — a
  // second partial refund on an already-partially-refunded order used to be
  // able to refund up to the full total again since nothing tracked how much
  // had already gone out.
  const alreadyRefunded = order.refunded_amount ?? 0
  const remaining = order.total_amount - alreadyRefunded
  const refundAmount = options?.amount ?? remaining
  if (refundAmount <= 0 || refundAmount > remaining) return { error: 'Invalid refund amount' }

  const gatewayResult = await issueGatewayRefund(order, refundAmount)
  if ('error' in gatewayResult) {
    // The attempt is recorded even though it failed — a refunds table holding
    // only successes cannot answer "what did we try and fail to return?", which
    // is the question someone asks after a customer chases them. The order is
    // flagged so it surfaces in the admin's needs-attention view rather than
    // looking settled.
    await recordRefund({
      orderId, gateway: order.payment_method ?? 'manual', amount: refundAmount,
      status: 'failed', reason: options?.reason, error: gatewayResult.error,
      actorEmail: actor.email,
    })
    await admin.from('orders').update({
      refund_needs_attention: true,
      admin_notes: [order.admin_notes, `REFUND FAILED — ₹${(refundAmount / 100).toLocaleString('en-IN')} not returned: ${gatewayResult.error}`].filter(Boolean).join('\n'),
    }).eq('id', orderId)
    await sendSlackAlert(
      `:rotating_light: Refund FAILED for order ${order.order_number} (₹${(refundAmount / 100).toLocaleString('en-IN')}): ${gatewayResult.error}`
    )
    return { error: gatewayResult.error }
  }

  const refundId = await recordRefund({
    orderId, gateway: order.payment_method ?? 'manual', amount: refundAmount,
    status: 'succeeded', gatewayRefundId: gatewayResult.gatewayRefundId,
    reason: options?.reason, actorEmail: actor.email,
  })

  // Section 34: reducing the value of a supply after its invoice was issued
  // needs a credit note, and without one the GST charged on the refunded part
  // is never reversed — the shop keeps owing the government tax on money it
  // gave back. Only applies to an order that was actually invoiced; a refund
  // before dispatch has no invoice to credit and is skipped silently.
  //
  // Deliberately after the money moved and after the refund is recorded: a
  // document problem must never roll back a refund the gateway has completed.
  if (refundId) {
    const { issueCreditNoteForRefund } = await import('@/lib/invoicing')
    const note = await issueCreditNoteForRefund(
      refundId,
      options?.reason ?? 'Refund',
      { actorId: actor.id }
    )
    if ('refused' in note) {
      console.warn(`[credit-note] not issued for refund ${refundId}: ${note.refused}`)
    }
  }

  const newRefundedAmount = alreadyRefunded + refundAmount
  const isFullyRefunded = newRefundedAmount >= order.total_amount
  const noteLine = `Refund issued: ₹${(refundAmount / 100).toLocaleString('en-IN')}${options?.reason ? ` — ${options.reason}` : ''}`
  const { error } = await admin.from('orders').update({
    payment_status: isFullyRefunded ? 'refunded' : 'partially_refunded',
    refunded_amount: newRefundedAmount,
    refund_needs_attention: false,
    admin_notes: [order.admin_notes, noteLine].filter(Boolean).join('\n'),
  }).eq('id', orderId)
  if (error) return { error: error.message }

  // Money left the business — this is the line an investigation starts from.
  await auditLog({
    actorId: actor.id, actorEmail: actor.email, action: 'order.refunded',
    entityType: 'order', entityId: orderId,
    before: { payment_status: order.payment_status, refunded_amount: alreadyRefunded },
    after: { refunded_amount: newRefundedAmount, fully_refunded: isFullyRefunded },
    note: options?.reason,
  })

  if (options?.restock !== false) {
    await restoreOrderStock(orderId)
  }
  // A fully-refunded order is, for the customer's coupon allowance, the same
  // as one that never completed — release it so the UNIQUE(coupon_id,
  // user_id) constraint (021) doesn't permanently lock them out of a code
  // they never actually got to use. Partial refunds leave the order
  // substantially standing, so the coupon usage stays counted.
  if (isFullyRefunded) {
    await releaseCouponUsage(orderId)
  }

  await sendRefundEmail({
    email: order.email,
    orderNumber: order.order_number,
    amount: refundAmount,
    partial: !isFullyRefunded,
  }).catch(() => {})

  revalidatePath(`/admin/orders`)
  revalidatePath(`/orders/${orderId}`)
  return { success: true }
}

/**
 * What this cart will actually cost, delivered to this address.
 *
 * Exists because the checkout screen used to show a subtotal and the words
 * "Shipping & tax: calculated after address" — on a page where the address is
 * already chosen — and then a Place Order button. The customer agreed to a
 * number nobody had shown them, and for cash on delivery a courier turned up
 * asking for it.
 *
 * Deliberately calls the SAME priceCheckout() that createOrder bills from, so
 * the quote and the charge cannot drift. If this returns 27943 paise, that is
 * what the order will be.
 *
 * Coupon errors come back as a normal result rather than a throw: a code that
 * stopped qualifying because the cart changed is an ordinary thing to tell
 * someone about, not an exception.
 */
export async function getCheckoutQuote(input: {
  userId?: string | null
  shipping_address_id: string
  coupon_code?: string
}) {
  const supabase = await createServerSupabaseClient()

  const cart = await getCart(input.userId, null, supabase)
  if (!cart?.items?.length) return { error: 'Cart is empty' as const }

  // RLS scopes addresses to their owner, so this cannot price against someone
  // else's address by id.
  const { data: address } = await supabase
    .from('addresses').select('*').eq('id', input.shipping_address_id).single()
  if (!address) return { error: 'Shipping address not found' as const }

  const priced = await priceCheckout({
    items: cart.items,
    destination: { state: address.state, country: address.country },
    couponCode: input.coupon_code,
    userId: input.userId ?? undefined,
    client: supabase,
  })
  if ('error' in priced) return { error: priced.error }

  // taxByLine is a Map and is only needed at insert time; it does not survive
  // the server-action boundary and has no business on the client anyway.
  return {
    subtotal: priced.subtotal,
    promotions: priced.promotions,
    couponDiscount: priced.couponDiscount,
    discountAmount: priced.discountAmount,
    shippingCost: priced.shippingCost,
    effectiveShipping: priced.effectiveShipping,
    freeShipping: priced.freeShipping,
    taxAmount: priced.taxAmount,
    taxBreakdown: priced.taxBreakdown,
    taxIsIgst: priced.taxIsIgst,
    taxEnabled: priced.taxEnabled,
    totalAmount: priced.totalAmount,
    destinationState: address.state as string | null,
    // So the summary can say WHY delivery is free rather than just showing a
    // zero. The owner read a bare "0" as a bug — it was the threshold working,
    // but an unexplained zero on a price line reads as broken either way.
    freeShippingThreshold: (await getStoreSettings()).free_shipping_threshold,
  }
}
