-- ============================================================================
-- Intentionally empty.
--
-- This migration used to insert a demo catalogue: 3 placeholder collections
-- (Mist & Morning, Silent Altitude, O Collection), 9 placeholder products
-- (Mist Tee, Dawn Jogger, Altitude Pack 40L, Summit Shell, …) and their
-- variants, all with stock Unsplash imagery.
--
-- Every one of those rows was hard-deleted from the live database by
-- 026_remove_seed_data.sql. This file is emptied rather than deleted so the
-- migration numbering stays contiguous with what has already been applied,
-- and — more importantly — so that provisioning a fresh environment from this
-- folder does NOT re-create the demo catalogue that 026 just removed.
--
-- The store's real catalogue is created through /admin. Do not add seed rows
-- here.
-- ============================================================================
